--- Dockerfile	2017-02-17 17:10:12.855604530 -0800
+++ Dockerfile	2017-02-17 17:10:33.063524996 -0800
@@ -1,6 +1,6 @@
 FROM openanalytics/r-base
 
-MAINTAINER Tobias Verbeke "tobias.verbeke@openanalytics.eu"
+MAINTAINER Brian High "brianhigh@github.com"
 
 # system libraries of general use
 RUN apt-get update && apt-get install -y \
@@ -14,22 +14,18 @@
     libssh2-1-dev \
     libssl1.0.0
 
-# system library dependency for the euler app
-RUN apt-get update && apt-get install -y \
-    libmpfr-dev
-
 # basic shiny functionality
 RUN R -e "install.packages(c('shiny', 'rmarkdown'), repos='https://cloud.r-project.org/')"
 
-# install dependencies of the euler app
-RUN R -e "install.packages('Rmpfr', repos='https://cloud.r-project.org/')"
+# install dependencies of the superzip app
+RUN R -e "install.packages(c('leaflet', 'RColorBrewer', 'scales', 'lattice', 'dplyr', 'DT'), repos='https://cloud.r-project.org/')"
 
 # copy the app to the image
-RUN mkdir /root/euler
-COPY euler /root/euler
+RUN mkdir /root/superzip
+COPY superzip /root/superzip
 
 COPY Rprofile.site /usr/lib/R/etc/
 
 EXPOSE 3838
 
-CMD ["R", "-e shiny::runApp('/root/euler')"]
+CMD ["R", "-e shiny::runApp('/root/superzip')"]
